name: Bug Report
description: Report a bug or unexpected behavior
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      placeholder: '@solid-foundation/primitive-button'
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the package are you using?
      placeholder: '0.0.0'
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      options:
        - Browser (Chrome, Firefox, Safari, etc.)
        - Node.js
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug clearly and concisely
      placeholder: 'A clear and concise description of what the bug is.'
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Provide a minimal code example that reproduces the issue
      placeholder: |
        ```tsx
        import { Button } from '@solid-foundation/primitive-button'

        function App() {
          return <Button>Click me</Button>
        }
        ```
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: 'Add any other context about the problem here, such as screenshots, OS, browser version, etc.'
